version: '3.8'

services:
  app:
    build: .
    container_name: milkshop_app
    restart: unless-stopped
    working_dir: /var/www/src
    user: "1000:www-data"
    volumes:
      - ./src:/var/www/src
    environment:
      - APP_URL=http://localhost:8181
      - ASSET_URL=http://localhost:8181
      - APP_ENV=local
      - SESSION_DOMAIN=null
      - SESSION_SECURE_COOKIE=false
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=milkshop
      - DB_USERNAME=milkshop
      - DB_PASSWORD=milkshop
    depends_on:
      - db
    ports:
      - "9000:9000"

  db:
    image: postgres:15
    container_name: milkshop_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: milkshop
      POSTGRES_USER: milkshop
      POSTGRES_PASSWORD: milkshop
    ports:
      - "5432:5432"
    volumes:
      - milkshop_pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: milkshop_nginx
    restart: unless-stopped
    ports:
      - "8181:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app

volumes:
  milkshop_pgdata:
